---
- hosts: centos 
  vars:
    - apache_packages_tmp:
      - http
      - mysql
  tasks:
    - name: Define apache_packages.
      set_fact:
        test: "{{ apache_packages_tmp | list }}"
#        result: "{{ apache_packages }}"
      register: test

    - name: show result tasks on screen 
      debug: var=test.stdout_lines