---
- name: play1 
  hosts: centos
  roles:
    - role: 'geerling.mysql'


#    - apache
#    - { role: geerling.mysql }
# vars:
#   tasks:
#    - name: Define packages.
#      set_fact:
#        pa: "{{ ___packages | list }}"
#   
#    - debug: 
#        msg: "{{ pa }}"

#######################################################################
