---
- name: play1 
  hosts: centos 
  tasks:
   - name: Include Apache 2.2 variables.
      vars: 
        - test: "apache-22.yml"
      set_facts: 
        result: "{{ test.split('.')[1] }}"
      register: result
      
    - debug:
        msg: "{{ result.stdout}}"