---
#Play: SETUP LAMP SERVER
- 
  name: PLAY1 - SETUP LAMP SERVER
  hosts: centos
  tasks:

    - name: Setup LAMP server
      yum: 
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - httpd
          - mariadb-server
          - php
      
    - name: Start and enabled services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - httpd
        - mariadb

    - name : check status
      #command: systemctl status mariadb
      command: curl http://localhost
      register: result

    - name: show result tasks on screen 
      debug: var=result.stdout_lines
################################################################
#PLAY2 - SET FIREALL CONFIGURATION
-
  name: PLAY2 - SET FIREALL CONFIGURATION
  hosts: centos
  vars:
    #http_port: 8081
    snmp_port: 160-161
    #inter_ip_range: 192.0.2.0
    
  tasks:
    - firewalld:
        service: http
        permanent: true
        state: enabled

     - firewalld:
        port: "{{ snmp_port }}/udp"
        permanent: true
        state: enabled

     - command: firewall-cmd --reload

    - name : check status
      command: firewall-cmd --list-all 
      register: result

    - name: show result tasks on screen 
      debug: var=result.stdout_lines
---
##################################################################