---
# tasks file for php

- name: 1a. install PHP module for Apache
  apt: name=libapache2-mod-php state=present

- name: 1b. install PHP module for nginx
  apt: name=php-fpm state=present

- name: 2. Install extension PHP for MySQL
  apt: name=php-mysql state=present

- name: 3. deploy Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664

- name: 4. deploy file db.php
  copy: src=db.php dest=/var/www/html/db.php mode=0644
