---
# tasks file for apache
- name: Install the correct web server for RHEL.
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian.
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

#config apache
- name: Configure Apache.
  include_tasks: "configure-{{ ansible_os_family }}.yml"